from hello_agents import SimpleAgent, HelloAgentsLLM
from tools.market_data import MarketDataService
import datetime
from typing import Dict, Any, Optional

class DailyReportAgent(SimpleAgent):
    """
    Agent responsible for generating daily investment reports.
    """
    
    def __init__(self, llm: HelloAgentsLLM, market_service: MarketDataService):
        super().__init__(
            name="Daily Report Agent",
            llm=llm,
            system_prompt="You are a professional investment advisor. Generate a concise, actionable daily report based on market data and portfolio performance."
        )
        self.market_service = market_service
        self._report_cache = {}  # date -> report_content

    async def generate_report(self, portfolio_summary: Dict[str, Any], user_id: str = "default") -> str:
        """
        Generate a daily report for the user.
        """
        today = datetime.date.today().isoformat()
        cache_key = f"{user_id}_{today}"
        
        # Return cached report if available
        if cache_key in self._report_cache:
            return self._report_cache[cache_key]

        # 1. Gather Market Data
        print("Gathering market data for daily report...")
        market_overview = await self._get_market_overview()
        
        # 2. Construt Prompt
        prompt = self._construct_prompt(market_overview, portfolio_summary)
        
        # 3. Call LLM
        # HelloAgents Agent.run() is synchronous or async? Most examples use run()
        # But here we are in async context. 
        # Checking strategist.py, it likely returns a string directly.
        print("Generating report with LLM...")
        report_content = self.run(prompt)
        
        # 4. Cache and Return
        self._report_cache[cache_key] = report_content
        return report_content

    async def _get_market_overview(self) -> str:
        """Helper to format market overview string"""
        try:
            # Use get_market_indices_async from MarketDataService
            indices = await self.market_service.get_market_indices_async()
            
            lines = []
            if indices:
                for idx in indices:
                    # idx is MarketIndexData object
                    name = idx.name
                    value = idx.price
                    # change_percent is float or str? MarketIndexData definition says float.
                    change = idx.change_percent
                    lines.append(f"- {name}: {value} ({change:+.2f}%)")
            
            if not lines:
                return "暂无法获取市场指数数据。"
                
            return "\n".join(lines)
            
        except Exception as e:
            print(f"Error getting market overview: {e}")
            return "市场数据获取失败。"

    def _construct_prompt(self, market_overview: str, portfolio: Dict[str, Any]) -> str:
        total_value = portfolio.get('total_value', 0)
        total_profit = portfolio.get('total_profit', 0)
        profit_rate = portfolio.get('total_profit_rate', 0)
        
        return f"""
Please generate a specific daily investment report for today ({datetime.date.today().isoformat()}).
Use Markdown format.

## Data Context

### Market Overview (China A-Shares)
{market_overview}

### User Portfolio
- Total Assets: ¥{total_value:,.2f}
- Total Profit: ¥{total_profit:,.2f}
- Return Rate: {profit_rate:+.2f}%

## Report Structure Required

# 📅 每日投资简报 ({datetime.date.today().isoformat()})

## 🌏 市场概况
[Summarize market performance in 2-3 sentences. Bullish or Bearish?]

## 💼 持仓分析
[Analyze user's portfolio performance relative to the market. Give a brief comment on the return rate.]

## 💡 投资建议
[Provide 2-3 specific, actionable points based on the current market sentiment. e.g., "Wait and see", "Buy the dip", "Reduce position". Be cautious but clear.]

---
*Note: This report is generated by AI for reference only.*
"""
